#! /usr/bin/ruby

puts %x(mkdir #{ARGV[0]})
puts %x(mkdir #{ARGV[0]}/build)
puts %x(cp ~/bin/xxxTest.cpp #{ARGV[0]}/#{ARGV[1]}Test.cpp)
puts %x(cp ~/bin/xxx.h #{ARGV[0]}/#{ARGV[1]}.h)
puts %x(cp main.cpp #{ARGV[0]}/main.cpp)
puts %x(cp CMakeLists.txt #{ARGV[0]}/CMakeLists.txt)
puts %x(cp inotifyrun #{ARGV[0]}/build/inotifyrun)
puts %x(cp mybuild #{ARGV[0]}/build/mybuild)





